wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: manurslf (manurslf301) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.19.8
wandb: Run data is saved locally in /home/users/r/rasolof2/BCs_emmanuelrasolofo/BCs_EmmanuelRasolofo/wandb/run-20250324_103803-oz8r8p03
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ACC_TOK midjourney dataset 20250324-103802
wandb: ‚≠êÔ∏è View project at https://wandb.ai/manurslf301/Encoder-DecoderProject
wandb: üöÄ View run at https://wandb.ai/manurslf301/Encoder-DecoderProject/runs/oz8r8p03
Training date: 20250324-103802
Images are resized 224x224
Additional token added : [0, 10, 30, 60]
Hidden layer LLMA : 1 with size 128
Batch size : 128, LR : 0.0004, epochs : 35
Traceback (most recent call last):
  File "/home/users/r/rasolof2/BCs_emmanuelrasolofo/BCs_EmmanuelRasolofo/utils.py", line 277, in <module>
    plot_accuracy(model,
                  ^^^^^
NameError: name 'model' is not defined
[1;34mwandb[0m: 
[1;34mwandb[0m: üöÄ View run [33mACC_TOK midjourney dataset 20250324-103802[0m at: [34mhttps://wandb.ai/manurslf301/Encoder-DecoderProject/runs/oz8r8p03[0m
[1;34mwandb[0m: Find logs at: [1;35mwandb/run-20250324_103803-oz8r8p03/logs[0m
srun: error: gpu002: task 0: Exited with exit code 1
